name: Node.js CI # Название workflow
on: # Когда workflow должен запускаться
  push:
    branches: [ "main" ] # Запускать при push в ветку main
  pull_request:
    branches: [ "main" ] # Запускать при создании pull request в main

jobs: # Описание работ
  build: # Имя работы
    runs-on: ubuntu-latest # На какой ОС запускать
    steps:
    - uses: actions/checkout@v3 # Скачивание кода из репозитория
    - name: Set up Node.js # Установка NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Версия NodeJS
    - name: Install dependencies # Установка зависимостей проекта
      run: npm install
    - name: Run tests # Запуск тестов
      run: npm test